#pragma once
#include "input.ui.h"

const int QUANTITY_OF_MENU_POINTS = 13;

enum MenuOptions {
	ENTER_INFORMATION_WITH_KEYBOARD = 1,
	ENTER_INFORMATION_FROM_CREATED_TEXT_FILE,
	ENTER_INFORMATION_FROM_CREATED_BINARY_FILE,
	OUTPUT_DATA_ON_DISPLAY,
	OUTPUT_DATA_TO_FILE,
	PRINT_DATA_SORTED_BY_AVERANGE_MARK,
	CONVERT_THE_DATABASE_TO_A_TEXT_FILE,
	CONVERT_THE_CONTENST_OF_THE_TEXT_FILE_TO_A_BINARY,
	CREATE_AN_ENTRY,
	UPDATE_AN_ENTRY,
	DELETE_AN_ENTRY,
	SORT,
	EXIT
};

struct MenuPoint {
	int number;
	void (*module)(Storage&);
	char name[OUTPUT_LENGTH];
};

// Module
void moduleMenu(Storage&);

